# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ba1054018906aa1f3225f3d88848b21d0ed3317409b46f7191c5118696f7fb9eb2e813eb5992669aebb01e6678a3becb349ff7d997bacd726ea327de62f14be

test:
  secret_key_base: 55f9c1abda9ac03358ac8f8fb2885f7fccfb0e38a09668f072ad8967fa27156c3f72a524147858cac85a3d3f8a75b963934d93d5704dca1752e667e910d3c800

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
